name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t whois-status-alert .

      - name: Tag Docker Image
        run: docker tag whois-status-alert:latest ${{ steps.login-ecr.outputs.registry }}/whois-status-alert:latest

      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/whois-status-alert:latest

    #   - name: Update Lambda function to use new image
    #     run: |
    #       aws lambda update-function-code --function-name my-lambda-function \
    #         --image-uri ${{ steps.login-ecr.outputs.registry }}/my-lambda-repo:latest